version: '2'
services:
  rtls_api_manager:
    container_name: rtls_api_manager
    image:  mibburo/rtls_api_manager:rtls_api_manager
    expose:
      - 7010
    ports:
      - 7010:7010
    environment:
      - KEY=secret
